name: Apply Kubernetes Deployment

# Trigger manually or on push to the main branch for the deployment.yaml file
on:
  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GKE_ZONE: europe-west2-c
  GKE_REGION: europe-west2 
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}

jobs:
  apply-deployment:
    environment: production
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_GITHUB_WIP }}
          service_account: ${{ secrets.GCP_GITHUB_SERVICE_ACCOUNT }}
          access_token_lifetime: '120s'

      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v2.2.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yaml

      - name: Show created Pods
        run: |
          kubectl get pods
