name: Deploy Node.JS Application Container

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
    branches: [ 'main' ]

  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  DOCKER_ARTIFACT_REPOSITORY: ${{ secrets.GCE_PROJECT_DOCKER_ARTIFACT_REGISTRY }}
  GKE_ZONE: europe-west2-c
  GKE_REGION: europe-west2 
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  AZTEVERIFY_IMAGE: azteverify-service

jobs:

  continuous-deployment:
    environment: production
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.release-store.outputs.NEW_TAG }}
      previous-tag: ${{ steps.release-store.outputs.PREV_TAG }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Generate next release number
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          dry_run: true

      - name: Generate SHA output
        id: vars
        run: echo "GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_GITHUB_WIP }}
          service_account: ${{ secrets.GCP_GITHUB_SERVICE_ACCOUNT }}
          access_token_lifetime: '120s'
      
      - uses: 'docker/login-action@v3'
        name: 'Docker login'
        with:
          registry: '${{ env.GKE_REGION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Docker build'
        run: |
          docker build --tag "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEVERIFY_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f Dockerfile .

      - name: 'Docker push'
        run: |
          docker push "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEVERIFY_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"
      
      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v2.2.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
      
      - name: Export deployment variables
        run: |
          export GCE_PROJECT="${{ env.PROJECT_ID }}"
          export GCE_PROJECT_DOCKER_ARTIFACT_REGISTRY="${{ env.DOCKER_ARTIFACT_REPOSITORY }}"
      
      - name: Remove previous deployments
        run: |
          kubectl delete deployment --ignore-not-found=true aztemarket-service-${{ steps.tag_version.outputs.previous_tag }}
      
      - name: Create GKE Deployments for new image
        run: |
          kubectl create deployment aztemarket-service-${{ steps.tag_version.outputs.new_tag }} --image="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEVERIFY_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"

      - name: Scale deployments
        run: |
          kubectl scale --replicas=1 deployment/aztemarket-service-${{ steps.tag_version.outputs.new_tag }}

      - name: Expose deployments
        run: |
          kubectl expose deployment/lavalink-service --type="LoadBalancer" --port=8080 --target-port=8080 --name=${{ env.AZTEVERIFY_IMAGE }}

      - name: Show created Pods
        run: |
          kubectl get pods
      
      - name: Create a new GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}